text = "PythonPrograms"
print("----text Indexing----")
print("original text:", text)
print("first character:", text[0])
print("last character:", text[-1])
print("fifth character:", text[4])
print("----text Slicing----")
print("first six characters:", text[:6])
print("Character 7 to 12:", text[6:12])
print("Every 2nd character:", text[::2])
print("Reverse text:", text[::-1])
num = [10,20,30,40,50,60,70]
print("----list Indexing----")
print("original list:", num)
print("first number:", num[0])
print("last number:", num[-1])
print("3rd number:", num[2])
print("----list Slicing----")
print("first four number:", num[:4])
print("number 4 to 7", num[3:7])
print("Every 2nd number:", num[::2])
print("Reverse string:", num[::-1])