import random

print("🎨 RANDOM EMOJI ART GENERATOR")
print("=" * 35)

emojis = ["🔥", "⭐", "💻", "🐍", "🚀", "❤️", "⚡", "🌟"]

for row in range(8):
    line = ""

    for column in range(8):
        line += random.choice(emojis) + " "

    print(line)

print("\n🎨 Art generated by Python!")
print("🐍 DAY 28/100 COMPLETE!")